#!/usr/bin/env bun
/**
 * Generate LaTeX listings index from manifest.yaml.
 * Output: papers/generated/listings-index.tex
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const PAPERS_DIR = join(import.meta.dir, "..");
const MANIFEST = join(PAPERS_DIR, "listings/manifest.yaml");
const OUT = join(PAPERS_DIR, "generated/listings-index.tex");

interface Entry {
  id: string;
  output: string;
  caption: string;
  source: string;
}

function parseManifest(raw: string): Entry[] {
  const entries: Entry[] = [];
  let cur: Partial<Entry> = {};
  for (const line of raw.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#") || t === "listings:") continue;
    const m = t.match(/^-?\s*([\w]+):\s*(.*)$/);
    if (!m) continue;
    const [, key, val] = m;
    const v = val.replace(/^["']|["']$/g, "");
    if (key === "id" && Object.keys(cur).length) {
      entries.push(cur as Entry);
      cur = {};
    }
    if (key === "id") cur.id = v;
    else if (key === "output") cur.output = v;
    else if (key === "caption") cur.caption = v;
    else if (key === "source") cur.source = v;
  }
  if (Object.keys(cur).length) entries.push(cur as Entry);
  return entries;
}

function category(source: string, id: string): string {
  if (id.startsWith("test-") || source.startsWith("tests/")) return "Tests";
  if (source.includes("hoox/")) return "Gateway";
  if (source.includes("web3-wallet-worker")) return "Web3 / DeFi";
  if (source.includes("trade-worker")) return "Execution";
  if (source.includes("agent-worker")) return "Agent / AI";
  if (source.includes("d1-worker") || source.includes("schema.sql") || source.includes("d1/"))
    return "Data layer";
  if (source.includes("analytics")) return "Observability";
  if (source.includes("email-worker")) return "Email ingress";
  if (source.includes("middleware") || source.includes("queue-handler") || source.includes("cron-handler"))
    return "Shared middleware";
  if (source.includes("wsAdapters") || source.includes("exchange-connection-manager"))
    return "WebSocket adapters";
  if (source.includes("exchanges") || source.includes("-client")) return "Exchange clients";
  if (source.endsWith(".jsonc") || source.includes("wrangler")) return "Configuration";
  return "Shared packages";
}

function esc(s: string): string {
  return s.replace(/[&%$#_{}]/g, (c) => `\\${c}`);
}

function main(): void {
  const entries = parseManifest(readFileSync(MANIFEST, "utf-8"));
  const byCat = new Map<string, Entry[]>();
  for (const e of entries) {
    const cat = category(e.source, e.id);
    if (!byCat.has(cat)) byCat.set(cat, []);
    byCat.get(cat)!.push(e);
  }

  const order = [
    "Gateway",
    "Execution",
    "Web3 / DeFi",
    "WebSocket adapters",
    "Exchange clients",
    "Agent / AI",
    "Data layer",
    "Observability",
    "Email ingress",
    "Shared middleware",
    "Shared packages",
    "Configuration",
    "Tests",
  ];

  const lines: string[] = [
    "% Auto-generated by papers/scripts/generate-listings-index.ts",
    `% Generated: ${new Date().toISOString()}`,
    `% ${entries.length} listings from manifest.yaml`,
    "",
  ];

  for (const cat of order) {
    const group = byCat.get(cat);
    if (!group?.length) continue;
    lines.push(`\\subsection{${esc(cat)}}`, "");
    lines.push("\\begin{table}[h]", "\\centering", "\\small");
    lines.push(`\\caption{Code listings: ${esc(cat).toLowerCase()}.}`);
    lines.push("\\begin{tabular}{@{}llp{6.2cm}@{}}", "\\toprule");
    lines.push("\\textbf{Label} & \\textbf{File} & \\textbf{Description} \\\\", "\\midrule");
    for (const e of group) {
      const label = `lst:${e.id}`;
      lines.push(
        `Listing~\\ref{${label}} & \\texttt{${esc(e.output)}} & ${esc(e.caption)} \\\\`
      );
    }
    lines.push("\\bottomrule", "\\end{tabular}", "\\end{table}", "");
  }

  mkdirSync(join(PAPERS_DIR, "generated"), { recursive: true });
  writeFileSync(OUT, lines.join("\n") + "\n", "utf-8");
  console.log(`Wrote ${OUT} (${entries.length} listings)`);
}

main();