#!/usr/bin/env bun
/**
 * Generate LaTeX table fragments from graph-metadata.json.
 *
 * Usage (from repo root):
 *   bun papers/scripts/sync-graph-tables.ts
 *
 * Output: papers/generated/graph-tables.tex
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dir, "../..");
const GRAPH_META = join(REPO_ROOT, "graph-metadata.json");
const OUT_DIR = join(REPO_ROOT, "papers/generated");
const OUT_FILE = join(OUT_DIR, "graph-tables.tex");

interface DataFlow {
  source: string;
  target: string;
  description: string;
  flowType?: string;
}

interface Community {
  id: string;
  label: string;
  description: string;
}

interface GraphMetadata {
  dataFlows?: DataFlow[];
  communities?: Community[];
}

function esc(s: string): string {
  return s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/[&%$#_{}]/g, (c) => `\\${c}`)
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function workerLabel(path: string): string {
  return path.replace(/^workers\//, "").replace(/\//g, "/");
}

function main(): void {
  const meta = JSON.parse(readFileSync(GRAPH_META, "utf-8")) as GraphMetadata;
  mkdirSync(OUT_DIR, { recursive: true });

  const lines: string[] = [
    "% Auto-generated by papers/scripts/sync-graph-tables.ts — do not edit by hand.",
    `% Generated: ${new Date().toISOString()}`,
    "% Included from appendices/E-graph-reference.tex (section header lives there).",
    "",
  ];

  const flows = meta.dataFlows ?? [];
  if (flows.length > 0) {
    lines.push(
      "\\subsection{Data-flow edges}",
      "",
      "\\begin{table}[h]",
      "\\centering",
      "\\caption{Primary data-flow edges (selected).}",
      "\\label{tab:graph-dataflows}",
      "\\small",
      "\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llp{6.8cm}@{}}",
      "\\toprule",
      "\\textbf{Source} & \\textbf{Target} & \\textbf{Description} \\\\",
      "\\midrule"
    );

    const maxRows = 20;
    for (const f of flows.slice(0, maxRows)) {
      lines.push(
        `\\texttt{${esc(workerLabel(f.source))}} & \\texttt{${esc(workerLabel(f.target))}} & ${esc(f.description)} \\\\`
      );
    }

    lines.push("\\bottomrule", "\\end{tabular*}", "\\end{table}", "");
  }

  const communities = meta.communities ?? [];
  if (communities.length > 0) {
    lines.push(
      "\\subsection{Architecture communities}",
      "",
      "\\begin{table}[h]",
      "\\centering",
      "\\caption{Logical node clusters in the code graph.}",
      "\\label{tab:graph-communities}",
      "\\small",
      "\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}llp{7.5cm}@{}}",
      "\\toprule",
      "\\textbf{ID} & \\textbf{Label} & \\textbf{Description} \\\\",
      "\\midrule"
    );

    for (const c of communities) {
      lines.push(
        `\\texttt{${esc(c.id)}} & ${esc(c.label)} & ${esc(c.description)} \\\\`
      );
    }

    lines.push("\\bottomrule", "\\end{tabular*}", "\\end{table}", "");
  }

  writeFileSync(OUT_FILE, lines.join("\n") + "\n", "utf-8");
  console.log(`Wrote ${OUT_FILE}`);
  console.log(
    `  ${flows.length} data-flow edges, ${communities.length} communities`
  );
}

main();
