[global]
cloudflare_api_token = "cfut_Q7jLzuf3IO1Gh1uvia8Fz2vpmW3I9CEcFcDDPJWmd1bc339d"
cloudflare_account_id = "debc6545e63bea36be059cbc82d80ec8"
cloudflare_secret_store_id = "48433bc559a943f09d9d6c622e188fd5"
subdomain_prefix = "cryptolinx"

[workers.d1-worker]
enabled = true
path = "workers/d1-worker"
secrets = [ ]
deployed_url = "https://d1-worker.cryptolinx.workers.dev"

  [workers.d1-worker.vars]
  database_name = "my-database"

[workers.telegram-worker]
enabled = true
path = "workers/telegram-worker"
vars = { }
secrets = [ "TELEGRAM_BOT_TOKEN" ]
deployed_url = "https://telegram-worker.cryptolinx.workers.dev"

[workers.trade-worker]
enabled = true
path = "workers/trade-worker"
vars = { }
secrets = [ "API_SERVICE_KEY" ]
deployed_url = "https://trade-worker.cryptolinx.workers.dev"

[workers.web3-wallet-worker]
enabled = true
path = "workers/web3-wallet-worker"
vars = { }
secrets = [ "MNEMONIC" ]
deployed_url = "https://web3-wallet-worker.cryptolinx.workers.dev"

[workers.hoox]
enabled = true
path = "workers/hoox"
description = "Central webhook processing and dynamic routing worker"
secrets = [ ]
deployed_url = "https://hoox.cryptolinx.workers.dev"

[workers.home-assistant]
enabled = false
path = "workers/home-assistant-worker"
vars = { }
secrets = [ "HA_TOKEN", "HA_SECURE_URL" ]

[workers.agent-worker]
enabled = false
path = "workers/agent-worker"
vars = { }
secrets = [ ]

[workers.email-worker]
enabled = true
path = "workers/email-worker"
secrets = [ "EMAIL_HOST", "EMAIL_USER", "EMAIL_PASS", "INTERNAL_KEY" ]
deployed_url = "https://email-worker.cryptolinx.workers.dev"

  [workers.email-worker.vars]
  USE_IMAP = "false"
