import * as p from "@clack/prompts";
import type { Command, CommandContext } from "../../core/types.js";
import { CLIError } from "../../core/errors.js";
import { randomUUID } from "crypto";

export class ConfigKeysCommand implements Command {
  name = "config:keys";
  description = "Generate/manage local .keys/*.env files";
  options = [
    {
      flag: "generate",
      short: "g",
      type: "boolean" as const,
      description: "Generate new key file",
    },
    {
      flag: "list",
      short: "l",
      type: "boolean" as const,
      description: "List all key files",
    },
    {
      flag: "key-name",
      type: "string" as const,
      description: "Key file name (without .env)",
    },
  ];

  async execute(ctx: CommandContext): Promise<void> {
    ctx.observer.emit("command:start", {
      cmd: this.name,
      args: {
        generate: ctx.args?.generate,
        list: ctx.args?.list,
        keyName: ctx.args?.keyName,
      },
    });

    try {
      p.intro("Local Keys Manager");

      const action = ctx.args?.generate
        ? "generate"
        : ctx.args?.list
          ? "list"
          : await p.select({
              message: "What would you like to do?",
              options: [
                { value: "generate", label: "Generate new key file" },
                { value: "list", label: "List all key files" },
              ],
            });

      if (p.isCancel(action)) {
        p.cancel("Operation cancelled.");
        return;
      }

      const spinner = p.spinner();

      if (action === "generate") {
        await this.generateKey(ctx, spinner);
      } else if (action === "list") {
        await this.listKeys(ctx, spinner);
      }

      p.outro("Keys operation completed!");
      ctx.observer.setState({ commandStatus: "success" });
    } catch (error) {
      const cliError =
        error instanceof CLIError
          ? error
          : new CLIError(
              `Keys command failed: ${error instanceof Error ? error.message : String(error)}`,
              "KEYS_FAILED",
              false
            );
      p.log.error(cliError.message);
      ctx.observer.setState({ commandStatus: "error", lastError: cliError });
    }
  }

  private async generateKey(
    ctx: CommandContext,
    spinner: ReturnType<typeof p.spinner>
  ): Promise<void> {
    let keyName = ctx.args?.keyName as string | undefined;

    if (!keyName) {
      const input = await p.text({
        message: "Enter key file name (without .env):",
        validate: (v) => (!v ? "Key name is required" : undefined),
      });
      if (p.isCancel(input)) {
        p.cancel("Operation cancelled.");
        return;
      }
      keyName = input;
    }

    // Generate a secure random key
    const apiKey = randomUUID();
    const secretKey = randomUUID();

    const keyContent = `# Generated by hoox config:keys on ${new Date().toISOString()}
API_KEY=${apiKey}
SECRET_KEY=${secretKey}
`;

    const keysDir = `${ctx.cwd}/.keys`;
    const keyFilePath = `${keysDir}/${keyName}.env`;

    spinner.start(`Generating key file ${keyName}.env...`);

    try {
      // Use bun adapter to write file
      await ctx.adapters.bun.writeFile(keyFilePath, keyContent);

      spinner.stop(`Key file generated: ${keyName}.env`);
      p.log.success(`Keys written to ${keyFilePath}`);
      p.log.warn(
        "Keep these files secure and never commit them to version control!"
      );
    } catch (error) {
      spinner.stop(`Failed to generate key file ${keyName}.env`, 1);
      throw error;
    }
  }

  private async listKeys(
    ctx: CommandContext,
    spinner: ReturnType<typeof p.spinner>
  ): Promise<void> {
    spinner.start("Listing key files...");

    try {
      // Use bun adapter to read the .keys directory
      const keysDir = `${ctx.cwd}/.keys`;

      // In a real implementation, this would use ctx.adapters.bun.readDir() or similar
      // For now, we'll simulate the operation
      await new Promise((resolve) => setTimeout(resolve, 500));

      spinner.stop("Key files listed!");
      p.log.info("No key files found (placeholder - implement with adapter)");
    } catch (error) {
      spinner.stop("Failed to list key files", 1);
      throw error;
    }
  }
}
