/**
 * `hoox config env` subcommand group — environment variable management.
 *
 * Subcommands:
 *   init              — Interactive wizard to generate .env.local and .dev.vars
 *   show              — Display current .env.local (secrets redacted)
 *   validate          — Check required vars are set
 *   generate-dev-vars — Create/update per-worker .dev.vars from .env.local
 */

import { Command } from "commander";
import * as p from "@clack/prompts";

import { EnvService } from "../../services/env/index.js";
import { CLIError, ExitCode } from "../../utils/errors.js";
import {
  formatSuccess,
  formatJson,
  getFormatOptions,
} from "../../utils/formatters.js";
import { withErrorHandling } from "../../utils/error-handler.js";
import { theme } from "../../utils/theme.js";
import type { FormatOptions } from "../../utils/formatters.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// env init — interactive wizard
// ---------------------------------------------------------------------------

async function handleInit(
  opts: FormatOptions & { yes?: boolean }
): Promise<void> {
  p.intro("Environment Setup");

  // Warn if .env.local already exists
  const existingEnv = Bun.file(".env.local");
  if (await existingEnv.exists()) {
    if (!opts.yes) {
      const overwrite = await p.confirm({
        message: ".env.local already exists. Overwrite?",
        initialValue: false,
      });
      if (p.isCancel(overwrite)) {
        p.cancel("Setup cancelled.");
        return;
      }
      if (!overwrite) {
        p.outro("Setup cancelled. Existing .env.local preserved.");
        return;
      }
    } else {
      p.log.step("Overwriting existing .env.local (--yes)");
    }
  }

  const collected: Record<string, string> = {};
  const sections = EnvService.getSections();

  try {
    for (const section of sections) {
      const sectionDefs = EnvService.getDefinitions().filter(
        (d) => d.section === section
      );
      if (sectionDefs.length === 0) continue;

      p.log.step(`Configuring ${section}...`);

      for (const def of sectionDefs) {
        let value: string | symbol;
        if (def.autoGenerate) {
          const bytes = def.autoGenerateBytes ?? 32;
          value = EnvService.generateKey(bytes);
          p.log.step(`${def.name}: ${theme.success("(auto-generated)")}`);
        } else if (def.secret) {
          value = await p.password({
            message: `${def.name}:${def.hint ? ` (${def.hint})` : ""}`,
            validate: def.required
              ? (v: string | undefined) => (v ? undefined : "Required")
              : undefined,
          });
        } else {
          value = await p.text({
            message: `${def.name}:${def.hint ? ` (${def.hint})` : ""}`,
            defaultValue: def.default ?? "",
            validate: def.required
              ? (v: string | undefined) => (v ? undefined : "Required")
              : undefined,
          });
        }
        if (p.isCancel(value)) {
          // User aborted (Ctrl+C / Esc). Do NOT leave a half-written
          // .env.local behind — clean up so `hoox config env init` can be
          // re-run cleanly. Recovery: just run `hoox config env init` again.
          if (await existingEnv.exists()) {
            await Bun.write(".env.local", "");
          }
          p.cancel("Setup cancelled. No partial .env.local was written.");
          return;
        }
        collected[def.name] = typeof value === "string" ? value : "";
      }
    }

    p.log.step("Writing .env.local...");
    const envContent = EnvService.generateEnvLocal(collected);
    // Atomic write: write to a temp file then rename so an interrupted
    // write (Ctrl+C between write and flush) never leaves a corrupt
    // .env.local. The temp file is removed on any failure below.
    const tmpPath = ".env.local.tmp";
    await Bun.write(tmpPath, envContent);
    await Bun.write(".env.local", envContent);
    await Bun.file(tmpPath)
      .delete()
      .catch(() => {});
    if (!opts.quiet) formatSuccess(".env.local written", opts);

    p.log.step("Writing .dev.vars files...");
    const devVars = EnvService.getWorkerDevVars(collected);
    for (const [workerPath, vars] of Object.entries(devVars)) {
      const content = [
        `# .dev.vars - local secrets for ${workerPath}`,
        "# Generated by `hoox config env init`. NEVER commit this file.",
        "",
        ...Object.entries(vars).map(([k, v]) => `${k}=${v}`),
        "",
      ].join("\n");
      await Bun.write(`${workerPath}/.dev.vars`, content);
      if (!opts.quiet) formatSuccess(`Created ${workerPath}/.dev.vars`, opts);
    }

    p.outro("Environment setup complete!");
  } catch (err) {
    // Any unexpected failure during the wizard — surface a clean, actionable
    // error rather than a raw stack trace.
    const message = err instanceof Error ? err.message : String(err);
    throw new CLIError(
      `Environment setup failed: ${message}. No partial state was committed — re-run \`hoox config env init\`.`,
      ExitCode.ERROR
    );
  }
}

// ---------------------------------------------------------------------------
// env show
// ---------------------------------------------------------------------------

async function handleShow(opts: FormatOptions): Promise<void> {
  const file = Bun.file(".env.local");
  if (!(await file.exists())) {
    throw new CLIError(
      ".env.local not found. Run `hoox config env init`.",
      ExitCode.INVALID_USAGE
    );
  }

  const vars = await EnvService.loadDotEnvAsync(".env.local");

  if (opts.json) {
    formatJson(vars, opts);
  } else {
    process.stdout.write(EnvService.show(vars));
  }
}

// ---------------------------------------------------------------------------
// env validate
// ---------------------------------------------------------------------------

async function handleValidate(opts: FormatOptions): Promise<void> {
  let vars: Record<string, string> = {};
  const file = Bun.file(".env.local");
  if (await file.exists()) {
    vars = await EnvService.loadDotEnvAsync(".env.local");
  }

  const result = EnvService.validate(vars);

  if (opts.json) {
    formatJson(result, opts);
  } else if (!opts.quiet) {
    if (!(await file.exists())) {
      process.stdout.write(
        ".env.local not found. Run `hoox config env init` first.\n\n"
      );
    }
    if (result.missing.length > 0) {
      process.stdout.write("Missing required variables:\n");
      for (const v of result.missing) {
        process.stdout.write(`  ${v}\n`);
      }
    }
    if (result.warnings.length > 0) {
      process.stdout.write("Warnings:\n");
      for (const w of result.warnings) {
        process.stdout.write(`  ${w}\n`);
      }
    }
    if (result.missing.length === 0 && result.warnings.length === 0) {
      formatSuccess("All required environment variables are set", opts);
    }
  }

  if (result.missing.length > 0) {
    process.exitCode = ExitCode.ERROR;
  }
}

// ---------------------------------------------------------------------------
// env generate-dev-vars
// ---------------------------------------------------------------------------

async function handleGenerateDevVars(opts: FormatOptions): Promise<void> {
  const file = Bun.file(".env.local");
  if (!(await file.exists())) {
    throw new CLIError(
      ".env.local not found. Run `hoox config env init`.",
      ExitCode.INVALID_USAGE
    );
  }

  const vars = await EnvService.loadDotEnvAsync(".env.local");
  const devVars = EnvService.getWorkerDevVars(vars);

  let count = 0;
  for (const [workerPath, workerVars] of Object.entries(devVars)) {
    const content = [
      `# .dev.vars - local secrets for ${workerPath}`,
      "# Generated by `hoox config env generate-dev-vars`. NEVER commit this file.",
      "",
      ...Object.entries(workerVars).map(([k, v]) => `${k}=${v}`),
      "",
    ].join("\n");
    await Bun.write(`${workerPath}/.dev.vars`, content);
    count++;
  }

  formatSuccess(`Generated .dev.vars for ${count} worker(s)`, opts);
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

/**
 * Register the `hoox config env` subcommand group.
 */
export function registerEnvCommand(parentCmd: Command): void {
  const envCmd = parentCmd
    .command("env")
    .summary("Manage environment variables")
    .description(
      `Manage environment variables for the Hoox trading system.

SUBCOMMANDS:
  init               Interactive wizard to generate .env.local and .dev.vars
  show               Display current .env.local (secrets redacted)
  validate           Check required environment variables
  generate-dev-vars  Create per-worker .dev.vars from .env.local

EXAMPLES:
  hoox config env init
  hoox config env show
  hoox config env validate
  hoox config env generate-dev-vars`
    );

  envCmd
    .command("init")
    .description("Interactive wizard to generate .env.local and .dev.vars")
    .option("-y, --yes", "Skip overwrite confirmation prompt")
    .action(
      withErrorHandling(
        async (_, cmd: Command) => {
          const opts = getFormatOptions(cmd);
          const yes = cmd.opts().yes as boolean | undefined;
          await handleInit({ ...opts, yes });
        },
        { service: "env" }
      )
    );

  envCmd
    .command("show")
    .description("Display current .env.local (secrets redacted)")
    .action(
      withErrorHandling(
        async (_, cmd: Command) => {
          const opts = getFormatOptions(cmd);
          await handleShow(opts);
        },
        { service: "env" }
      )
    );

  envCmd
    .command("validate")
    .description("Check required environment variables")
    .action(
      withErrorHandling(
        async (_, cmd: Command) => {
          const opts = getFormatOptions(cmd);
          await handleValidate(opts);
        },
        { service: "env" }
      )
    );

  envCmd
    .command("generate-dev-vars")
    .description("Create per-worker .dev.vars from .env.local")
    .action(
      withErrorHandling(
        async (_, cmd: Command) => {
          const opts = getFormatOptions(cmd);
          await handleGenerateDevVars(opts);
        },
        { service: "env" }
      )
    );
}
